### ISSUE TITLE
mappen structuur Layouts en sublayouts liefst als twee aparte mappen ivm extend

### ISSUE THREAD

**Issue by ghost** [PimDerks/front-end-boilerplate#39]
sublayouts word ook gebruikt voor grids die homepage extenden

**Comment by PimDerks** [comment]
Een layout die de master-layout extend is m.i. geen sub-layout. Sowieso denk ik dat het wellicht slimmer is om grid-structuren in je /prototype/ te zetten als dit pagina-specifiek is. Je wilt niet per pagina én een bestand in /prototype/ hebben én een layout.
